#!/bin/sh
# 03/03/17 - Created by Andrew Puckett
# 06/06/17 - Add redirect for www subdomain

if [ $# -lt 2 ]; then
	echo "NAME"
	echo "	$(basename $0) options"
	echo
	echo "DESCRIPTION"
	echo "	$(basename $0) is used to add a vhost to apache."
	echo
	echo "OPTIONS"
	echo "	-c"
	echo "	    Use certificates."
	echo "	-d"
	echo "	    Domain. Required."
	echo "	-i"
	echo "	    Install directory. Optional. If -c is used the key and pem files should be here. The conf file will be copied here as well."
	echo "	-n"
	echo "	    Name of host. Required."
	echo "	-r"
	echo "	    Redirect to this domain."
	echo
	echo "AUTHOR"
	echo "	Andrew Puckett"
	echo
	exit 1
fi

[ $(id -u) != "0" ] && echo "ERROR: You must be the superuser to run this script" >&2 && exit 1

CERT=0
REDIRECT=
INSTALL_DIR=.
CERT_DIR=/etc/ssl/certs
KEY_DIR=/etc/ssl/private
ETC_DIR=/etc/apache2/sites-available
VHOST_DIR=/var/www

while getopts cd:i:n:r: opt
do
	case "$opt"
	in
		c) CERT=1;;
		d) DOMAIN=$OPTARG;;
		i) INSTALL_DIR=$OPTARG;;
		n) SHORT_NAME=$OPTARG;;
		r) REDIRECT=$OPTARG;;
	esac
done

[ -z "$REDIRECT" ] && REDIRECT=$DOMAIN
[ -z "$DOMAIN" ] && echo "ERROR: Domain is required." >&2 && exit 1
[ -z "$SHORT_NAME" ] && echo "ERROR: Name is required." >&2 && exit 1

if [ $CERT -eq 1 ]; then
	cp --backup=numbered $INSTALL_DIR/$SHORT_NAME.pem $CERT_DIR/$SHORT_NAME.pem
	cp --backup=numbered $INSTALL_DIR/$SHORT_NAME.key $KEY_DIR/$SHORT_NAME.key
	chmod 600 $KEY_DIR/$SHORT_NAME.key
else
	cp --backup=numbered $CERT_DIR/ssl-cert-snakeoil.pem $CERT_DIR/$SHORT_NAME.pem
	cp --backup=numbered $KEY_DIR/ssl-cert-snakeoil.key $KEY_DIR/$SHORT_NAME.key
fi

cat > $INSTALL_DIR/$SHORT_NAME.conf <<- EOM
<VirtualHost *:80>
  ServerName $DOMAIN
  ServerAlias www.$DOMAIN
  Redirect permanent / https://$REDIRECT/
  SetEnvIf Request_URI "^/$" dontlog
  CustomLog \${APACHE_LOG_DIR}/${SHORT_NAME}_access.log combined env=!dontlog
</VirtualHost>

<IfModule mod_ssl.c>
  <VirtualHost *:443>
EOM

if [ "$REDIRECT" = "$DOMAIN" ]; then
	mkdir -p $VHOST_DIR/$SHORT_NAME
	cat >> $INSTALL_DIR/$SHORT_NAME.conf <<- EOM
	    ServerName www.$DOMAIN
	    SSLEngine on
	    SSLCertificateFile	$CERT_DIR/$SHORT_NAME.pem
	    SSLCertificateKeyFile $KEY_DIR/$SHORT_NAME.key
	    Redirect permanent / https://$REDIRECT/
	    SetEnvIf Request_URI "^/$" dontlog
	    CustomLog \${APACHE_LOG_DIR}/${SHORT_NAME}_access.log combined env=!dontlog
	  </VirtualHost>
	  <VirtualHost *:443>
	    ServerName $DOMAIN
	    SSLEngine on
	    SSLCertificateFile	$CERT_DIR/$SHORT_NAME.pem
	    SSLCertificateKeyFile $KEY_DIR/$SHORT_NAME.key

	    ServerAdmin admin@$DOMAIN
	    DocumentRoot $VHOST_DIR/$SHORT_NAME

	    ErrorLog \${APACHE_LOG_DIR}/${SHORT_NAME}_error.log
	    CustomLog \${APACHE_LOG_DIR}/${SHORT_NAME}_access.log combined

	    FileETag -INode
	    TraceEnable Off
	    <Directory $VHOST_DIR/$SHORT_NAME>
	      Options -Indexes
	    </Directory>
	    RedirectMatch 404 ^/inc|^/core|^/lib|^/conf|^/vendor

	    ErrorDocument 400 /error.html?q=400
	    ErrorDocument 401 /error.html?q=401
	    ErrorDocument 403 /error.html?q=403
	    ErrorDocument 404 /error.html?q=404
	    ErrorDocument 500 /error.html?q=500

	    <IfModule mod_expires.c>
	      <FilesMatch "\.(jpe?g|png|gif|js|css|ico)$">
	        ExpiresActive On
	        ExpiresDefault "access plus 1 week"
	      </FilesMatch>
	    </IfModule>

	    <FilesMatch "\.(cgi|shtml|phtml|php)$">
	      SSLOptions +StdEnvVars
	    </FilesMatch>
	    <Directory /usr/lib/cgi-bin>
	      SSLOptions +StdEnvVars
	    </Directory>
	    # MSIE 7 and newer should be able to use keepalive
	    BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown
	  </VirtualHost>
	</IfModule>
	EOM
else
	cat >> $INSTALL_DIR/$SHORT_NAME.conf <<- EOM
	    ServerName $DOMAIN
	    ServerAlias www.$DOMAIN
	    SSLEngine on
	    SSLCertificateFile	$CERT_DIR/$SHORT_NAME.pem
	    SSLCertificateKeyFile $KEY_DIR/$SHORT_NAME.key
	    Redirect permanent / https://$REDIRECT/
	    SetEnvIf Request_URI "^/$" dontlog
	    CustomLog \${APACHE_LOG_DIR}/${SHORT_NAME}_access.log combined env=!dontlog
	  </VirtualHost>
	</IfModule>
	EOM
fi

cp --backup=numbered $INSTALL_DIR/$SHORT_NAME.conf $ETC_DIR/$SHORT_NAME.conf

a2ensite $SHORT_NAME
apachectl configtest
