#!/bin/sh
# Add Domain to Postfix
# 08/16/17 - Created by Andrew Puckett

if [ $# -lt 2 ]; then
	echo "NAME"
	echo "	$(basename $0) options"
	echo
	echo "DESCRIPTION"
	echo "	$(basename $0) is used to add a domain to postfix."
	echo
	echo "OPTIONS"
	echo "	-a"
	echo "	    Email address to forward admin mail to."
	echo "	-d"
	echo "	    Domain. Required."
	echo "	-n"
	echo "	    Name of host (abbreviation). Required."
	echo
	echo "AUTHOR"
	echo "	Andrew Puckett"
	echo
	exit 1
fi

[ $(id -u) != "0" ] && echo "ERROR: You must be the superuser to run this script" >&2 && exit 1

DOMAIN=
SHORT_NAME=
ADMIN_EMAIL=

while getopts a:d:n: opt
do
	case "$opt" in
		a) ADMIN_EMAIL=$OPTARG;;
		d) DOMAIN=$OPTARG;;
		n) SHORT_NAME=$OPTARG;;
	esac
done

[ -f /etc/opendkim/signing.table ] && cat /etc/opendkim/signing.table > /etc/opendkim/signing.table_new
echo "*@$DOMAIN $SHORT_NAME" >> /etc/opendkim/signing.table_new
mv --backup=numbered /etc/opendkim/signing.table_new /etc/opendkim/signing.table

yes "y" | opendkim_add_key -d $DOMAIN -n $SHORT_NAME

[ -f /etc/postfix/virtual ] && cat /etc/postfix/virtual > /etc/postfix/virtual_new
echo $DOMAIN -- >> /etc/postfix/virtual_new
for ACCT in abuse accounts contact ftp hostmaster info list mail marketing postmaster root sales security social support webmaster www
do
	case "$ACCT" in
		accounts|postmaster|root|security|webmaster) echo $ACCT@$DOMAIN admin@$DOMAIN >> /etc/postfix/virtual_new;;
		mail|marketing|sales) echo $ACCT@$DOMAIN info@$DOMAIN >> /etc/postfix/virtual_new;;
		abuse|contact|info|list|social|support) echo $ACCT@$DOMAIN postmaster@$DOMAIN >> /etc/postfix/virtual_new;;
		ftp|hostmaster|www) echo $ACCT@$DOMAIN webmaster@$DOMAIN >> /etc/postfix/virtual_new;;
	esac
done

[ -n "$ADMIN_EMAIL" ] && echo admin@$DOMAIN $ADMIN_EMAIL >> /etc/postfix/virtual_new
mv --backup=numbered /etc/postfix/virtual_new /etc/postfix/virtual
postmap /etc/postfix/virtual