#! /bin/sh
# Script to display important server stats
#
# uptime (minutes)
# cpuX (percent) (X = '', 1, ...)
# loadavg (percent)
# cpu_apache2 (percent)
# cpu_mysqld (percent)
# mem (bytes)
# mem% (percent)
# swap (bytes)
# swap% (percent)
# mem_apache2 (bytes)
# mem_mysqld (bytes)
# xvdaX_reads (count) (X = '', 1, ...)
# xvdaX_readtime (ms) (X = '', 1, ...)
# xvdaX_writes (count) (X = '', 1, ...)
# xvdaX_writetime (ms) (X = '', 1, ...)
# xvdaX_used (bytes) (X = 1, 2, ...)
# xvdaX_used% (percent) (X = 1, 2, ...)
# ethX_rx (bytes) (X = 0, 1, ...)
# ethX_tx (bytes) (X = 0, 1, ...)
# 01/30/17 - Created by Andrew Puckett
# 06/06/17 - Added mem% and dev% and cleaned up code

cat /proc/uptime | awk '{print "uptime "$1}'
cat /proc/stat | awk '/cpu/ {print$1,($2+$4)*100/($2+$4+$5+$9)}'
cat /proc/loadavg | awk '{print "loadavg "$1}'
ps -C apache2,httpd -o pcpu | awk '{ sum += $1 } END { print "cpu_apache "sum }'
ps -C mysqld -o pcpu | awk '{ sum += $1 } END { print "cpu_mysqld "sum }'
free | awk '/Mem:/ {print "mem "$2-$7"\nmem% "100*($2-$7)/$2}'
free | awk '/Swap:/ {if($2 != 0){print "swap "$3"\nswap% "100*$3/$2}}'

if [ $(id -u) = "0" ]; then
	for var in apache2 mysqld; do
		mem=0
		for pid in $(pgrep $var); do
			#it's possible that the pid is no longer alive by the time we read it so ignore errors here
			mem=$((mem + $(awk '/^Pss:/{ sum += $2 } END { print sum }' /proc/$pid/smaps))) 2>/dev/null
		done
		echo mem_$var $mem
	done
else
	echo Run as root for additional data >&2
fi

cat /proc/diskstats | awk '/d/ {print $3"_reads " $4"\n" $3"_readtime " $7"\n" $3"_writes " $8"\n" $3"_writetime " $11}'

df | awk '/^\/dev/ {sub("/dev/","",$1);sub("%","",$5); print $1"_used "$3"\n"$1"_used% " $5}'

ip -s -o -a link | awk '{sub(":","", $2) } {print $2"_rx " $28"\n" $2"_tx "$43}'
#some implementations provide different information so adjust the indices accordingly
#ip -s -o -a link | awk '{sub(":","", $2) } {print $2"_rx " $26"\n" $2"_tx "$41}'
